"""
Mine the issues/comments from the Zephyr GitHub repository and check if comment 
contains information about the use of GenAI, then saved that comment and the user
who made the comment in a csv file.

Users who made comments containing information about the use of GenAI will be recorded in the csv file.

We need to find the first comment date they talked about using AI if they made multiple comments.

There is also a tag that can be checked that identifies the use of AI.

Users who admit to using AI versus users who use the tag should be distinguished in the csv file.

"""

genai_keywords = [
    "chatgpt", "gpt-3", "gpt-4", "gpt-4o", "gpt-5", "openai",
    "copilot", "claude", "anthropic", "gemini", "bard", "cursor",
    "llm", "large language model", "artificial intelligence",
    "ai-generated", "ai generated", "generated by ai", "written by ai",
    "used ai", "using ai", "ai assistant", "ai tool", "ai",
    
]

def mine_genai_comments():
    """
    Mine the issues/comments from the Zephyr GitHub repository and check if comment 
    contains information about the use of GenAI, then save that comment and the user
    who made the comment in a csv file.
    """
    pass


def check_genai_tag():
    """
    Check if a comment contains a tag that identifies the use of AI.
    """
    pass


def comment_contains_ai(comment: str):
    """
    Check if a comment contains information about the use of GenAI.
    """
    
    comment_lower = comment.lower()
    for keyword in genai_keywords:
        if keyword in comment_lower:
            return True
    return False