"""
Mine the pull requests/comments from the Zephyr GitHub repository and check if comment
contains information about the use of GenAI, then saved that comment and the user
who made the comment in a csv file.

Users who made comments containing information about the use of GenAI will be recorded in the csv file.

We need to find the first comment date they talked about using AI if they made multiple comments.

There is also a tag that can be checked that identifies the use of AI.

Users who admit to using AI versus users who use the tag should be distinguished in the csv file.

"""

import csv
import json
import os
import re
from datetime import datetime

from api import fetch_all_pages, fetch_request, get_session
from CONSTANTS import (
    AI_ASSISTED_LABEL,
    COMMENTS_DIR,
    COMMITS_DIR,
    CSV_FIELDS,
    CSV_PATH,
    DATA_DIR,
    DESCRIPTIONS_DIR,
    DISCUSSIONS_DIR,
    PARAMS,
    PULLS_URL,
    pr_comments_url,
    pr_commits_url,
    pr_review_comments_url,
    pr_reviews_url,
    start_date,
)

genai_keywords = [
    "chatgpt", "gpt-3", "gpt-4", "gpt-4o", "gpt-5", "openai",
    "copilot", "claude", "anthropic", "gemini", "bard", "cursor",
    "llm", "large language model", "artificial intelligence",
    "ai-generated", "ai generated", "generated by ai", "written by ai",
    "used ai", "using ai", "ai assistant", "ai tool", "ai", "assisted-by",
    
]

def mine_genai_comments():
    """
    Mine the issues/comments from the Zephyr GitHub repository and check if comment 
    contains information about the use of GenAI, then save that comment and the user
    who made the comment in a csv file.
    """
    pass


def check_genai_tag():
    """
    Check if a comment contains a tag that identifies the use of AI.
    """
    pass


def comment_contains_ai(comment: str):
    """
    Check if a comment contains information about the use of GenAI.
    """
    
    comment_lower = comment.lower()
    for keyword in genai_keywords:
        if keyword == "ai":
            if re.search(r"\bai\b", comment_lower):
                return True
        elif keyword in comment_lower:
            return True
        
    return False


def normalize_thread(raw_items, text_key, out_key):
    """GitHub comment/review objects -> our {id, name, created_at, comment/message} shape."""
    return [
        {
            "id": item["id"],
            "name": (item.get("user") or {}).get("login"),
            "created_at": item.get("created_at") or item.get("submitted_at"),
            out_key: item[text_key],
        }
        for item in raw_items
        if item.get(text_key)
    ]


def save_thread(directory, pr_number, items):
    """Write the comment/discussion thread for one PR to {directory}/{pr_number}.json.

    Returns the path relative to DATA_DIR (for the CSV row, so links stay valid
    no matter where the repo is checked out), or "" if there was nothing to save.
    """
    if not items:
        return ""
    os.makedirs(directory, exist_ok=True)
    path = os.path.join(directory, f"{pr_number}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(items, f, indent=2)
    return os.path.relpath(path, DATA_DIR).replace(os.sep, "/")


def save_text(directory, pr_number, text):
    """Write a single text blob (description/commit message) to {directory}/{pr_number}.txt.

    Returns the path relative to DATA_DIR (for the CSV row, so links stay valid
    no matter where the repo is checked out), or "" if there was nothing to save.
    """
    if not text:
        return ""
    os.makedirs(directory, exist_ok=True)
    path = os.path.join(directory, f"{pr_number}.txt")
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    return os.path.relpath(path, DATA_DIR).replace(os.sep, "/")


def mine_single_pr(session, pr):
    """Fetch comments/discussion/commits for one PR and return its CSV row."""
    pr_number = pr["number"]

    comments_resp = fetch_request(session, pr_comments_url(pr_number))
    review_comments_resp = fetch_request(session, pr_review_comments_url(pr_number))
    reviews_resp = fetch_request(session, pr_reviews_url(pr_number))
    commits_resp = fetch_request(session, pr_commits_url(pr_number))

    comments = normalize_thread(comments_resp.json() if comments_resp else [], "body", "comment")
    review_comments = normalize_thread(review_comments_resp.json() if review_comments_resp else [], "body", "message")
    reviews = normalize_thread(reviews_resp.json() if reviews_resp else [], "body", "message")
    commits = commits_resp.json() if commits_resp else []

    discussion = sorted(review_comments + reviews, key=lambda item: item["created_at"] or "")
    first_commit_message = commits[0]["commit"]["message"] if commits else ""

    pr_description = pr.get("body") or ""

    (
    ai_keyword_desc,
    ai_keyword_comments,
    ai_keyword_discussion,
    ai_keyword_commits,
    ) = contains_ai_keyword(
    pr_description,
    comments,
    discussion,
    first_commit_message
    )

    return {
        "pr_number": pr_number,
        "pr_creator": (pr.get("user") or {}).get("login"),
        "ai_assisted": any(
            label.get("name", "").strip().lower() == AI_ASSISTED_LABEL.lower()
            for label in pr.get("labels", [])
        ),
        "pr_desc": save_text(DESCRIPTIONS_DIR, pr_number, pr.get("body") or ""),
        "ai_keyword_desc": ai_keyword_desc,
        "pr_comments": save_thread(COMMENTS_DIR, pr_number, comments),
        "ai_keyword_comments": ai_keyword_comments,
        "pr_discussion": save_thread(DISCUSSIONS_DIR, pr_number, discussion),
        "ai_keyword_discussion": ai_keyword_discussion,
        "pr_commits": save_text(COMMITS_DIR, pr_number, first_commit_message),
        "ai_keyword_commits": ai_keyword_commits,
    }


def mine_pull_requests(limit=None):
    """One pass over /pulls: for every PR in range, fetch its details and write
    a row to the CSV immediately, so progress survives an interruption.

    `limit`, if given, stops after that many PRs (for quick test runs).
    """
    os.makedirs(DATA_DIR, exist_ok=True)
    session = get_session()

    write_header = not os.path.exists(CSV_PATH)
    with open(CSV_PATH, "a", newline="", encoding="utf-8") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=CSV_FIELDS)
        if write_header:
            writer.writeheader()

        mined = 0
        for page in fetch_all_pages(session, PULLS_URL, params=PARAMS):
            for pr in page:
                created_at = datetime.strptime(pr["created_at"], "%Y-%m-%dT%H:%M:%SZ")
                if created_at < start_date:
                    # PRs are sorted newest-first, so everything after this is too old.
                    return

                writer.writerow(mine_single_pr(session, pr))
                csv_file.flush()
                print(f"mined PR #{pr['number']} ({created_at.date()})")

                mined += 1
                if limit is not None and mined >= limit:
                    return


def contains_ai_keyword(pr_description, comments, discussion, commit_message):
    description_has_ai = comment_contains_ai(pr_description)

    comments_have_ai = False
    for comment in comments:
        if comment_contains_ai(comment.get("comment", "")):
            comments_have_ai = True
            break

    discussion_has_ai = False
    for item in discussion:
        text = item.get("comment", "")
        if not text:
            text = item.get("message", "")

        if comment_contains_ai(text):
            discussion_has_ai = True
            break

    commit_has_ai = comment_contains_ai(commit_message)

    return (
        description_has_ai,
        comments_have_ai,
        discussion_has_ai,
        commit_has_ai,
    )


if __name__ == "__main__":
    limit = os.environ.get("PR_LIMIT")
    mine_pull_requests(limit=int(limit) if limit else None)